name: aapt2 build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup cloudflared ssh
      - uses: valeriangalliat/action-sshd-cloudflared@v2
